name: cd

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'which version to bump(major, minor, patch, premajor, preminor, prepatch, prerelease)'
        required: true
        default: 'prerelease'
      force:
        description: 'force release even if no update(set --force-publish if necessary)'
        required: false
        default: ''

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Checkout release branch
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

          
      - name: Generate Template Zip Files
        run: .github/scripts/template-zip-autogen.sh ${{ github.ref }}

      - name: release daily npm packages to npmjs.org
        if: ${{ github.ref == 'refs/heads/dev' && startsWith(github.event.inputs.version, 'pre') }}
        run: |
          git tag --force templates@0.0.0-daily
          git push origin --force templates@0.0.0-daily
        
      - name: release daily templates
        if: ${{ github.ref == 'refs/heads/dev' && startsWith(github.event.inputs.version, 'pre') }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ./*.zip
          name: 'Release for templates 0.0.0-daily'
          token: ${{ secrets.github_token }}
          tag: '0.0.0-alpha'
          allowUpdates: true

      - name: release rc npm packages to npmjs.org
        if: ${{ startsWith(github.ref, 'refs/heads/release/') && github.event.inputs.version == 'prerelease' }}
        run: |
          git tag --force templates@0.0.0-alpha
          git push origin --force templates@0.0.0-alpha
          
      - name: release prerelease templates
        if: ${{ startsWith(github.ref, 'refs/heads/release/') && github.event.inputs.version == 'prerelease' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ./*.zip
          name: 'Release for templates 0.0.0-alpha'
          token: ${{ secrets.github_token }}
          tag: '0.0.0-alpha'
          allowUpdates: true

      - name: cleanup templates
        run: |
          rm -rf ./*zip
