name: cd

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'which version to bump(major, minor, patch, premajor, preminor, prepatch, prerelease)'
        required: true
        default: 'prerelease'
      force:
        description: 'force release even if no update(set --force-publish if necessary)'
        required: false
        default: ''

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Checkout release branch
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: generate templates
        run: .github/scripts/template-zip-autogen.sh

      - name: release templates' daily version to github
        if: ${{ github.ref == 'refs/heads/dev' && startsWith(github.event.inputs.version, 'pre') }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN  }}
          prerelease: true
          automatic_release_tag: "templates@0.0.0-daily"
          files: |
            ./*.zip

      - name: release templates' prerelease version to github
        if: ${{ startsWith(github.ref, 'refs/heads/release/') && github.event.inputs.version == 'prerelease' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN  }}
          prerelease: true
          automatic_release_tag: "templates@0.0.0-alpha"
          files: |
            ./*.zip

      - name: cleanup templates
        run: rm -rf ./*.zip

      - name: cleanup templates
        run: |
          rm -rf ./*zip
