name: lint 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: lint code on (${{ matrix.os }} with node ${{ matrix.node-version }})

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: |
          npm install
          npm run bootstrap
      - name: Lint code
        run: |
          npm run lint
